# Generated by Django 3.1.5 on 2021-01-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210126_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='expected_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
