# Generated by Django 3.1.5 on 2021-01-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210126_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=10)),
                ('contact_email', models.EmailField(max_length=50)),
                ('organization_name', models.CharField(max_length=50)),
                ('required_qualification', models.TextField(blank=True, max_length=50)),
                ('required_experience', models.CharField(blank=True, max_length=50)),
                ('salary_offering', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
