# Generated by Django 3.1.5 on 2021-01-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20210126_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uid', models.CharField(max_length=16)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(max_length=255)),
                ('file_document', models.FileField(upload_to='uploaded_files/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=16)),
            ],
        ),
    ]
